server:
  build: ./docker/server/production
  volumes:
    - ./docker/server/production/sites-enabled/:/etc/apache2/sites-enabled/
    - ./docker/server/production/php/php.ini:/usr/local/etc/php/conf.d/30-custom.ini
    - ./docker/server/production/php/xdebug.ini:/usr/local/etc/php/conf.d/50-xdebug.ini
    - ./www/html/production:/var/www/html
  environment:
    - APP_ENV=production
    - APP_DEBUG=false
    - APP_KEY=DdQr2jPqj5SvoY3jveIY6hfCMakJKaEY
    - DB_CONNECTION=pgsql
    - DB_HOST=postgres
    - DB_DATABASE=data
    - DB_USERNAME=admindata
    - DB_PASSWORD=ght2qir2m1

    - FACEBOOK_ID=1090097681002559
    - FACEBOOK_SECRET_CLIENT=fe2b1c6aff63424f2a5b3e2cbdcafc12
    - FACEBOOK_CALLBACK=http://automated-blogger.com/admin/callback/facebook
  ports:
    - 80:80
  links:
    - postgres:postgres

postgres:
  image: postgres
  volumes:
    - ./var/local/postgresql:/var/lib/postgresql/data
  environment:
    - POSTGRES_DB=data
    - POSTGRES_USER=admindata
    - POSTGRES_PASSWORD=ght2qir2m1
    - PGDATA=/var/lib/postgresql/data