server:
  build: ./docker/server/production
  volumes:
    - ./docker/server/production/sites-enabled/:/etc/apache2/sites-enabled/
    - ./docker/server/production/php/php.ini:/usr/local/etc/php/conf.d/30-custom.ini
    - ./docker/server/production/php/xdebug.ini:/usr/local/etc/php/conf.d/50-xdebug.ini
    - ./www/html/production:/var/www/html
  environment:
    - APP_ENV=production
    - APP_DEBUG=false
    - APP_KEY=DdQr2jPqj5SvoY3jveIY6hfCMakJKaEY
    - QUEUE_DRIVER=database
    - DB_CONNECTION=pgsql
    - DB_HOST=postgres
    - DB_DATABASE=data
    - DB_USERNAME=admindata
    - DB_PASSWORD=ght2qir2m1

    - PAYPAL_CLIENT_ID=AWGZvWDxf4R_2TKMGIZyOKTGb4kRj4XtiyYt3a5W4HENkcPPLn_pMWw1ciwCOhL5WT6MFeKyUi5SspYp
    - PAYPAL_SECRET_ID=EKNtJQhz3mrSa0vzP3lVmpVn5cNgZAx1IPwsN82yUhi7DAv35HjVvJ4N3EKT4jj2H-f1R5ZcSXtZrlXx

    - STRIPE_KEY=pk_live_rwRMsryGJbYdIF4p6cx6GJ3n
    - STRIPE_SECRET=sk_live_ET2S8k7U1Sbrjp6HrK8QzayY

    - FACEBOOK_ID=1090097681002559
    - FACEBOOK_SECRET_CLIENT=fe2b1c6aff63424f2a5b3e2cbdcafc12
    - FACEBOOK_CALLBACK=http://automated-blogger.com/admin/callback/facebook

    - YOUTUBE_API_KEY=AIzaSyCrTGoLnxj9XPxXoAgS8aXp5oI8Mib6sm0
    - YOUTUBE_ID=499070319532-s6m1svpm3sfm5uu1bhhntecvcclq8151.apps.googleusercontent.com
    - YOUTUBE_SECRET_CLIENT=6Q1fawBiUrKwWIKls2Ch9e8m
    - YOUTUBE_CALLBACK=http://automated-blogger.com/admin/callback/youtube

    - APP_DEFAULT_DOMAIN=automated-blogger
    - SERVICE_PAYMENT=stripe
  ports:
    - 80:80
  links:
    - postgres:postgres

postgres:
  image: postgres
  volumes:
    - ./var/local/postgresql:/var/lib/postgresql/data
  environment:
    - POSTGRES_DB=data
    - POSTGRES_USER=admindata
    - POSTGRES_PASSWORD=ght2qir2m1
    - PGDATA=/var/lib/postgresql/data